/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.MyLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyLanguageStandaloneSetup extends MyLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    MyLanguageStandaloneSetup _myLanguageStandaloneSetup = new MyLanguageStandaloneSetup();
    _myLanguageStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
