/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.example.mydsl.myLanguage.TestFile;
import org.xtext.example.mydsl.tests.MyLanguageInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(MyLanguageInjectorProvider.class)
@SuppressWarnings("all")
public class MyLanguageParsingTest {
  @Inject
  private ParseHelper<TestFile> parseHelper;
  
  @Test
  public void loadModel() {
    Assert.assertNotNull(Integer.valueOf(1));
  }
}
