/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CENTIMETER</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getCENTIMETER()
 * @model
 * @generated
 */
public interface CENTIMETER extends DistanceUnit
{
} // CENTIMETER
