/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Distance To Obstacles Sent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.DistanceToObstaclesSent#getBody <em>Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.DistanceToObstaclesSent#getTolerance <em>Tolerance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getDistanceToObstaclesSent()
 * @model
 * @generated
 */
public interface DistanceToObstaclesSent extends EObject
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(EObject)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getDistanceToObstaclesSent_Body()
   * @model containment="true"
   * @generated
   */
  EObject getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.DistanceToObstaclesSent#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(EObject value);

  /**
   * Returns the value of the '<em><b>Tolerance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tolerance</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tolerance</em>' containment reference.
   * @see #setTolerance(ToleranceSent)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getDistanceToObstaclesSent_Tolerance()
   * @model containment="true"
   * @generated
   */
  ToleranceSent getTolerance();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.DistanceToObstaclesSent#getTolerance <em>Tolerance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tolerance</em>' containment reference.
   * @see #getTolerance()
   * @generated
   */
  void setTolerance(ToleranceSent value);

} // DistanceToObstaclesSent
