/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mission Sent</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getMissionSent()
 * @model
 * @generated
 */
public interface MissionSent extends StatementBody
{
} // MissionSent
