/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Payload Sent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.PayloadSent#getLoad <em>Load</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getPayloadSent()
 * @model
 * @generated
 */
public interface PayloadSent extends Robot
{
  /**
   * Returns the value of the '<em><b>Load</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Load</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Load</em>' attribute.
   * @see #setLoad(String)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getPayloadSent_Load()
   * @model
   * @generated
   */
  String getLoad();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.PayloadSent#getLoad <em>Load</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Load</em>' attribute.
   * @see #getLoad()
   * @generated
   */
  void setLoad(String value);

} // PayloadSent
