/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot Speed Sent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.RobotSpeedSent#getSpeed <em>Speed</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getRobotSpeedSent()
 * @model
 * @generated
 */
public interface RobotSpeedSent extends Robot
{
  /**
   * Returns the value of the '<em><b>Speed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speed</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' containment reference.
   * @see #setSpeed(SpeedUnit)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getRobotSpeedSent_Speed()
   * @model containment="true"
   * @generated
   */
  SpeedUnit getSpeed();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.RobotSpeedSent#getSpeed <em>Speed</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' containment reference.
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(SpeedUnit value);

} // RobotSpeedSent
