/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot Position Sent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getPosX <em>Pos X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getPosY <em>Pos Y</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getPosZ <em>Pos Z</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getTolerance <em>Tolerance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getRobotPositionSent()
 * @model
 * @generated
 */
public interface RobotPositionSent extends Robot
{
  /**
   * Returns the value of the '<em><b>Pos X</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pos X</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos X</em>' containment reference.
   * @see #setPosX(DistanceUnit)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getRobotPositionSent_PosX()
   * @model containment="true"
   * @generated
   */
  DistanceUnit getPosX();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getPosX <em>Pos X</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos X</em>' containment reference.
   * @see #getPosX()
   * @generated
   */
  void setPosX(DistanceUnit value);

  /**
   * Returns the value of the '<em><b>Pos Y</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pos Y</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos Y</em>' containment reference.
   * @see #setPosY(DistanceUnit)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getRobotPositionSent_PosY()
   * @model containment="true"
   * @generated
   */
  DistanceUnit getPosY();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getPosY <em>Pos Y</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos Y</em>' containment reference.
   * @see #getPosY()
   * @generated
   */
  void setPosY(DistanceUnit value);

  /**
   * Returns the value of the '<em><b>Pos Z</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pos Z</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pos Z</em>' containment reference.
   * @see #setPosZ(DistanceUnit)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getRobotPositionSent_PosZ()
   * @model containment="true"
   * @generated
   */
  DistanceUnit getPosZ();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getPosZ <em>Pos Z</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pos Z</em>' containment reference.
   * @see #getPosZ()
   * @generated
   */
  void setPosZ(DistanceUnit value);

  /**
   * Returns the value of the '<em><b>Tolerance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tolerance</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tolerance</em>' containment reference.
   * @see #setTolerance(EObject)
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#getRobotPositionSent_Tolerance()
   * @model containment="true"
   * @generated
   */
  EObject getTolerance();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myLanguage.RobotPositionSent#getTolerance <em>Tolerance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tolerance</em>' containment reference.
   * @see #getTolerance()
   * @generated
   */
  void setTolerance(EObject value);

} // RobotPositionSent
