/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.example.mydsl.myLanguage.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage
 * @generated
 */
public class MyLanguageSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MyLanguagePackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyLanguageSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = MyLanguagePackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case MyLanguagePackage.TEST_FILE:
      {
        TestFile testFile = (TestFile)theEObject;
        T result = caseTestFile(testFile);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.TEST:
      {
        Test test = (Test)theEObject;
        T result = caseTest(test);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.STATEMENT:
      {
        Statement statement = (Statement)theEObject;
        T result = caseStatement(statement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.GIVEN:
      {
        Given given = (Given)theEObject;
        T result = caseGiven(given);
        if (result == null) result = caseStatement(given);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.THEN:
      {
        Then then = (Then)theEObject;
        T result = caseThen(then);
        if (result == null) result = caseStatement(then);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.WHEN:
      {
        When when = (When)theEObject;
        T result = caseWhen(when);
        if (result == null) result = caseStatement(when);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.STATEMENT_BODY:
      {
        StatementBody statementBody = (StatementBody)theEObject;
        T result = caseStatementBody(statementBody);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.COMP_STATUS_SENT:
      {
        CompStatusSent compStatusSent = (CompStatusSent)theEObject;
        T result = caseCompStatusSent(compStatusSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.BARO_SENT:
      {
        BaroSent baroSent = (BaroSent)theEObject;
        T result = caseBaroSent(baroSent);
        if (result == null) result = caseStatementBody(baroSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.BARO_ALT_SENT:
      {
        BaroAltSent baroAltSent = (BaroAltSent)theEObject;
        T result = caseBaroAltSent(baroAltSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.SONAR_SENT:
      {
        SonarSent sonarSent = (SonarSent)theEObject;
        T result = caseSonarSent(sonarSent);
        if (result == null) result = caseStatementBody(sonarSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.SONAR_DISTANCE_SENT:
      {
        SonarDistanceSent sonarDistanceSent = (SonarDistanceSent)theEObject;
        T result = caseSonarDistanceSent(sonarDistanceSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.NOTIFICATION_SENT:
      {
        NotificationSent notificationSent = (NotificationSent)theEObject;
        T result = caseNotificationSent(notificationSent);
        if (result == null) result = caseStatementBody(notificationSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.TIME_SENT:
      {
        TimeSent timeSent = (TimeSent)theEObject;
        T result = caseTimeSent(timeSent);
        if (result == null) result = caseStatementBody(timeSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.TIME_INTERVAL:
      {
        TimeInterval timeInterval = (TimeInterval)theEObject;
        T result = caseTimeInterval(timeInterval);
        if (result == null) result = caseTimeSent(timeInterval);
        if (result == null) result = caseStatementBody(timeInterval);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.BATTERY_SENT:
      {
        BatterySent batterySent = (BatterySent)theEObject;
        T result = caseBatterySent(batterySent);
        if (result == null) result = caseStatementBody(batterySent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.BATTERY_LEVEL_SENT:
      {
        BatteryLevelSent batteryLevelSent = (BatteryLevelSent)theEObject;
        T result = caseBatteryLevelSent(batteryLevelSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.PEOPLE_SENT:
      {
        PeopleSent peopleSent = (PeopleSent)theEObject;
        T result = casePeopleSent(peopleSent);
        if (result == null) result = caseStatementBody(peopleSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.PEOPLE_POS_SENT:
      {
        PeoplePosSent peoplePosSent = (PeoplePosSent)theEObject;
        T result = casePeoplePosSent(peoplePosSent);
        if (result == null) result = casePeopleSent(peoplePosSent);
        if (result == null) result = caseStatementBody(peoplePosSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.PEOPLE_NUMB_SENT:
      {
        PeopleNumbSent peopleNumbSent = (PeopleNumbSent)theEObject;
        T result = casePeopleNumbSent(peopleNumbSent);
        if (result == null) result = casePeopleSent(peopleNumbSent);
        if (result == null) result = caseStatementBody(peopleNumbSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.MISSION_SENT:
      {
        MissionSent missionSent = (MissionSent)theEObject;
        T result = caseMissionSent(missionSent);
        if (result == null) result = caseStatementBody(missionSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.MISSION_GOAL_SENT:
      {
        MissionGoalSent missionGoalSent = (MissionGoalSent)theEObject;
        T result = caseMissionGoalSent(missionGoalSent);
        if (result == null) result = caseMissionSent(missionGoalSent);
        if (result == null) result = caseStatementBody(missionGoalSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.MISSION_RISK_LEVEL_SENT:
      {
        MissionRiskLevelSent missionRiskLevelSent = (MissionRiskLevelSent)theEObject;
        T result = caseMissionRiskLevelSent(missionRiskLevelSent);
        if (result == null) result = caseMissionSent(missionRiskLevelSent);
        if (result == null) result = caseStatementBody(missionRiskLevelSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.MISSION_STATUS_SENT:
      {
        MissionStatusSent missionStatusSent = (MissionStatusSent)theEObject;
        T result = caseMissionStatusSent(missionStatusSent);
        if (result == null) result = caseMissionSent(missionStatusSent);
        if (result == null) result = caseStatementBody(missionStatusSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.ROBOT:
      {
        Robot robot = (Robot)theEObject;
        T result = caseRobot(robot);
        if (result == null) result = caseStatementBody(robot);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.ROBOT_AUTO_PILOT:
      {
        RobotAutoPilot robotAutoPilot = (RobotAutoPilot)theEObject;
        T result = caseRobotAutoPilot(robotAutoPilot);
        if (result == null) result = caseRobot(robotAutoPilot);
        if (result == null) result = caseStatementBody(robotAutoPilot);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.PAYLOAD_SENT:
      {
        PayloadSent payloadSent = (PayloadSent)theEObject;
        T result = casePayloadSent(payloadSent);
        if (result == null) result = caseRobot(payloadSent);
        if (result == null) result = caseStatementBody(payloadSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.ROBOT_DISTANCE_SENT:
      {
        RobotDistanceSent robotDistanceSent = (RobotDistanceSent)theEObject;
        T result = caseRobotDistanceSent(robotDistanceSent);
        if (result == null) result = caseRobot(robotDistanceSent);
        if (result == null) result = caseStatementBody(robotDistanceSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.DISTANCE_TO_LOCATION_SENT:
      {
        DistanceToLocationSent distanceToLocationSent = (DistanceToLocationSent)theEObject;
        T result = caseDistanceToLocationSent(distanceToLocationSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT:
      {
        DistanceToObstaclesSent distanceToObstaclesSent = (DistanceToObstaclesSent)theEObject;
        T result = caseDistanceToObstaclesSent(distanceToObstaclesSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.EQUAL_SENT:
      {
        EqualSent equalSent = (EqualSent)theEObject;
        T result = caseEqualSent(equalSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.LESS_SENT:
      {
        LessSent lessSent = (LessSent)theEObject;
        T result = caseLessSent(lessSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.GREATER_SENT:
      {
        GreaterSent greaterSent = (GreaterSent)theEObject;
        T result = caseGreaterSent(greaterSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.ROBOT_STATE_SENT:
      {
        RobotStateSent robotStateSent = (RobotStateSent)theEObject;
        T result = caseRobotStateSent(robotStateSent);
        if (result == null) result = caseRobot(robotStateSent);
        if (result == null) result = caseStatementBody(robotStateSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.ROBOT_POSITION_SENT:
      {
        RobotPositionSent robotPositionSent = (RobotPositionSent)theEObject;
        T result = caseRobotPositionSent(robotPositionSent);
        if (result == null) result = caseRobot(robotPositionSent);
        if (result == null) result = caseStatementBody(robotPositionSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.CIRCLE_POSITION:
      {
        CirclePosition circlePosition = (CirclePosition)theEObject;
        T result = caseCirclePosition(circlePosition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.SPHERE_POSITION:
      {
        SpherePosition spherePosition = (SpherePosition)theEObject;
        T result = caseSpherePosition(spherePosition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.ROBOT_SPEED_SENT:
      {
        RobotSpeedSent robotSpeedSent = (RobotSpeedSent)theEObject;
        T result = caseRobotSpeedSent(robotSpeedSent);
        if (result == null) result = caseRobot(robotSpeedSent);
        if (result == null) result = caseStatementBody(robotSpeedSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.ENVIRONMENT_SENT:
      {
        EnvironmentSent environmentSent = (EnvironmentSent)theEObject;
        T result = caseEnvironmentSent(environmentSent);
        if (result == null) result = caseStatementBody(environmentSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.RISK_SENT:
      {
        RiskSent riskSent = (RiskSent)theEObject;
        T result = caseRiskSent(riskSent);
        if (result == null) result = caseRobot(riskSent);
        if (result == null) result = caseStatementBody(riskSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.TOLERANCE_SENT:
      {
        ToleranceSent toleranceSent = (ToleranceSent)theEObject;
        T result = caseToleranceSent(toleranceSent);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.DISTANCE_UNIT:
      {
        DistanceUnit distanceUnit = (DistanceUnit)theEObject;
        T result = caseDistanceUnit(distanceUnit);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.TIME_UNIT:
      {
        TimeUnit timeUnit = (TimeUnit)theEObject;
        T result = caseTimeUnit(timeUnit);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.SECONDS:
      {
        SECONDS seconds = (SECONDS)theEObject;
        T result = caseSECONDS(seconds);
        if (result == null) result = caseTimeUnit(seconds);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.HOUR:
      {
        HOUR hour = (HOUR)theEObject;
        T result = caseHOUR(hour);
        if (result == null) result = caseTimeUnit(hour);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.MINUTES:
      {
        MINUTES minutes = (MINUTES)theEObject;
        T result = caseMINUTES(minutes);
        if (result == null) result = caseTimeUnit(minutes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.METER:
      {
        METER meter = (METER)theEObject;
        T result = caseMETER(meter);
        if (result == null) result = caseDistanceUnit(meter);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.CENTIMETER:
      {
        CENTIMETER centimeter = (CENTIMETER)theEObject;
        T result = caseCENTIMETER(centimeter);
        if (result == null) result = caseDistanceUnit(centimeter);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.MILLIMETER:
      {
        MILLIMETER millimeter = (MILLIMETER)theEObject;
        T result = caseMILLIMETER(millimeter);
        if (result == null) result = caseDistanceUnit(millimeter);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.KILOMETER:
      {
        KILOMETER kilometer = (KILOMETER)theEObject;
        T result = caseKILOMETER(kilometer);
        if (result == null) result = caseDistanceUnit(kilometer);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyLanguagePackage.PERCENT_UNIT:
      {
        PercentUnit percentUnit = (PercentUnit)theEObject;
        T result = casePercentUnit(percentUnit);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Test File</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Test File</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTestFile(TestFile object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Test</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Test</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTest(Test object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStatement(Statement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Given</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Given</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseGiven(Given object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Then</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Then</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseThen(Then object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>When</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>When</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWhen(When object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Statement Body</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Statement Body</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStatementBody(StatementBody object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Comp Status Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Comp Status Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCompStatusSent(CompStatusSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Baro Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Baro Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBaroSent(BaroSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Baro Alt Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Baro Alt Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBaroAltSent(BaroAltSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sonar Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sonar Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSonarSent(SonarSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sonar Distance Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sonar Distance Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSonarDistanceSent(SonarDistanceSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Notification Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Notification Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNotificationSent(NotificationSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Time Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Time Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTimeSent(TimeSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Time Interval</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Time Interval</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTimeInterval(TimeInterval object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Battery Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Battery Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBatterySent(BatterySent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Battery Level Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Battery Level Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBatteryLevelSent(BatteryLevelSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>People Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>People Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePeopleSent(PeopleSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>People Pos Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>People Pos Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePeoplePosSent(PeoplePosSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>People Numb Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>People Numb Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePeopleNumbSent(PeopleNumbSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Mission Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Mission Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMissionSent(MissionSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Mission Goal Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Mission Goal Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMissionGoalSent(MissionGoalSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Mission Risk Level Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Mission Risk Level Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMissionRiskLevelSent(MissionRiskLevelSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Mission Status Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Mission Status Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMissionStatusSent(MissionStatusSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Robot</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Robot</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRobot(Robot object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Robot Auto Pilot</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Robot Auto Pilot</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRobotAutoPilot(RobotAutoPilot object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Payload Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Payload Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePayloadSent(PayloadSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Robot Distance Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Robot Distance Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRobotDistanceSent(RobotDistanceSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Distance To Location Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Distance To Location Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDistanceToLocationSent(DistanceToLocationSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Distance To Obstacles Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Distance To Obstacles Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDistanceToObstaclesSent(DistanceToObstaclesSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Equal Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Equal Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEqualSent(EqualSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Less Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Less Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLessSent(LessSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Greater Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Greater Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseGreaterSent(GreaterSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Robot State Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Robot State Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRobotStateSent(RobotStateSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Robot Position Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Robot Position Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRobotPositionSent(RobotPositionSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Circle Position</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Circle Position</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCirclePosition(CirclePosition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sphere Position</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sphere Position</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSpherePosition(SpherePosition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Robot Speed Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Robot Speed Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRobotSpeedSent(RobotSpeedSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Environment Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Environment Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEnvironmentSent(EnvironmentSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Risk Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Risk Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRiskSent(RiskSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Tolerance Sent</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Tolerance Sent</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseToleranceSent(ToleranceSent object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Distance Unit</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Distance Unit</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDistanceUnit(DistanceUnit object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Time Unit</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Time Unit</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTimeUnit(TimeUnit object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>SECONDS</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>SECONDS</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSECONDS(SECONDS object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>HOUR</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>HOUR</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseHOUR(HOUR object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>MINUTES</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>MINUTES</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMINUTES(MINUTES object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>METER</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>METER</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMETER(METER object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>CENTIMETER</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>CENTIMETER</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCENTIMETER(CENTIMETER object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>MILLIMETER</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>MILLIMETER</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMILLIMETER(MILLIMETER object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>KILOMETER</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>KILOMETER</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseKILOMETER(KILOMETER object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Percent Unit</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Percent Unit</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePercentUnit(PercentUnit object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //MyLanguageSwitch
