/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myLanguage.DistanceToObstaclesSent;
import org.xtext.example.mydsl.myLanguage.MyLanguagePackage;
import org.xtext.example.mydsl.myLanguage.ToleranceSent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Distance To Obstacles Sent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.impl.DistanceToObstaclesSentImpl#getBody <em>Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.impl.DistanceToObstaclesSentImpl#getTolerance <em>Tolerance</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DistanceToObstaclesSentImpl extends MinimalEObjectImpl.Container implements DistanceToObstaclesSent
{
  /**
   * The cached value of the '{@link #getBody() <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBody()
   * @generated
   * @ordered
   */
  protected EObject body;

  /**
   * The cached value of the '{@link #getTolerance() <em>Tolerance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTolerance()
   * @generated
   * @ordered
   */
  protected ToleranceSent tolerance;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DistanceToObstaclesSentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyLanguagePackage.Literals.DISTANCE_TO_OBSTACLES_SENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getBody()
  {
    return body;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBody(EObject newBody, NotificationChain msgs)
  {
    EObject oldBody = body;
    body = newBody;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY, oldBody, newBody);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBody(EObject newBody)
  {
    if (newBody != body)
    {
      NotificationChain msgs = null;
      if (body != null)
        msgs = ((InternalEObject)body).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY, null, msgs);
      if (newBody != null)
        msgs = ((InternalEObject)newBody).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY, null, msgs);
      msgs = basicSetBody(newBody, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY, newBody, newBody));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ToleranceSent getTolerance()
  {
    return tolerance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTolerance(ToleranceSent newTolerance, NotificationChain msgs)
  {
    ToleranceSent oldTolerance = tolerance;
    tolerance = newTolerance;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE, oldTolerance, newTolerance);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTolerance(ToleranceSent newTolerance)
  {
    if (newTolerance != tolerance)
    {
      NotificationChain msgs = null;
      if (tolerance != null)
        msgs = ((InternalEObject)tolerance).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE, null, msgs);
      if (newTolerance != null)
        msgs = ((InternalEObject)newTolerance).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE, null, msgs);
      msgs = basicSetTolerance(newTolerance, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE, newTolerance, newTolerance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY:
        return basicSetBody(null, msgs);
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE:
        return basicSetTolerance(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY:
        return getBody();
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE:
        return getTolerance();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY:
        setBody((EObject)newValue);
        return;
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE:
        setTolerance((ToleranceSent)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY:
        setBody((EObject)null);
        return;
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE:
        setTolerance((ToleranceSent)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__BODY:
        return body != null;
      case MyLanguagePackage.DISTANCE_TO_OBSTACLES_SENT__TOLERANCE:
        return tolerance != null;
    }
    return super.eIsSet(featureID);
  }

} //DistanceToObstaclesSentImpl
