/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myLanguage.HOUR;
import org.xtext.example.mydsl.myLanguage.MyLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>HOUR</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HOURImpl extends TimeUnitImpl implements HOUR
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HOURImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyLanguagePackage.Literals.HOUR;
  }

} //HOURImpl
