/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myLanguage.METER;
import org.xtext.example.mydsl.myLanguage.MyLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>METER</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class METERImpl extends DistanceUnitImpl implements METER
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected METERImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyLanguagePackage.Literals.METER;
  }

} //METERImpl
