/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.myLanguage.BatterySent;
import org.xtext.example.mydsl.myLanguage.CirclePosition;
import org.xtext.example.mydsl.myLanguage.DistanceToLocationSent;
import org.xtext.example.mydsl.myLanguage.DistanceToObstaclesSent;
import org.xtext.example.mydsl.myLanguage.DistanceUnit;
import org.xtext.example.mydsl.myLanguage.EnvironmentSent;
import org.xtext.example.mydsl.myLanguage.EqualSent;
import org.xtext.example.mydsl.myLanguage.FailingComponentSent;
import org.xtext.example.mydsl.myLanguage.Given;
import org.xtext.example.mydsl.myLanguage.GreaterSent;
import org.xtext.example.mydsl.myLanguage.LessSent;
import org.xtext.example.mydsl.myLanguage.MissionGoalSent;
import org.xtext.example.mydsl.myLanguage.MissionRiskLevelSent;
import org.xtext.example.mydsl.myLanguage.MissionSent;
import org.xtext.example.mydsl.myLanguage.MissionStatusSent;
import org.xtext.example.mydsl.myLanguage.MyLanguageFactory;
import org.xtext.example.mydsl.myLanguage.MyLanguagePackage;
import org.xtext.example.mydsl.myLanguage.NotificationSent;
import org.xtext.example.mydsl.myLanguage.PayloadSent;
import org.xtext.example.mydsl.myLanguage.PeopleNumbSent;
import org.xtext.example.mydsl.myLanguage.PeoplePosSent;
import org.xtext.example.mydsl.myLanguage.PeopleSent;
import org.xtext.example.mydsl.myLanguage.PercentUnit;
import org.xtext.example.mydsl.myLanguage.RedundantComponent;
import org.xtext.example.mydsl.myLanguage.RiskSent;
import org.xtext.example.mydsl.myLanguage.Robot;
import org.xtext.example.mydsl.myLanguage.RobotAutoPilot;
import org.xtext.example.mydsl.myLanguage.RobotDistanceSent;
import org.xtext.example.mydsl.myLanguage.RobotPositionSent;
import org.xtext.example.mydsl.myLanguage.RobotSpeedSent;
import org.xtext.example.mydsl.myLanguage.RobotStateSent;
import org.xtext.example.mydsl.myLanguage.SonarSent;
import org.xtext.example.mydsl.myLanguage.SpherePosition;
import org.xtext.example.mydsl.myLanguage.Statement;
import org.xtext.example.mydsl.myLanguage.StatementBody;
import org.xtext.example.mydsl.myLanguage.Test;
import org.xtext.example.mydsl.myLanguage.TestFile;
import org.xtext.example.mydsl.myLanguage.Then;
import org.xtext.example.mydsl.myLanguage.TimeInterval;
import org.xtext.example.mydsl.myLanguage.TimeSent;
import org.xtext.example.mydsl.myLanguage.TimeUnit;
import org.xtext.example.mydsl.myLanguage.ToleranceSent;
import org.xtext.example.mydsl.myLanguage.When;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyLanguagePackageImpl extends EPackageImpl implements MyLanguagePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass testFileEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass testEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass givenEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass thenEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass whenEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statementBodyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sonarSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass notificationSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeIntervalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass batterySentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass peopleSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass peoplePosSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass peopleNumbSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass missionSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass missionGoalSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass missionRiskLevelSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass missionStatusSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass robotEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass robotAutoPilotEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass redundantComponentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass payloadSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass robotDistanceSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass distanceToLocationSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass distanceToObstaclesSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass equalSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lessSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass greaterSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass robotStateSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass robotPositionSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass circlePositionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass spherePositionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass robotSpeedSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass environmentSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass failingComponentSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass riskSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass toleranceSentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass distanceUnitEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeUnitEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secondsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass hourEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass minutesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass meterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass centimeterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass millimeterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass kilometerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass percentUnitEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.myLanguage.MyLanguagePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MyLanguagePackageImpl()
  {
    super(eNS_URI, MyLanguageFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link MyLanguagePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MyLanguagePackage init()
  {
    if (isInited) return (MyLanguagePackage)EPackage.Registry.INSTANCE.getEPackage(MyLanguagePackage.eNS_URI);

    // Obtain or create and register package
    MyLanguagePackageImpl theMyLanguagePackage = (MyLanguagePackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof MyLanguagePackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new MyLanguagePackageImpl());

    isInited = true;

    // Create package meta-data objects
    theMyLanguagePackage.createPackageContents();

    // Initialize created meta-data
    theMyLanguagePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMyLanguagePackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MyLanguagePackage.eNS_URI, theMyLanguagePackage);
    return theMyLanguagePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTestFile()
  {
    return testFileEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTestFile_Tests()
  {
    return (EReference)testFileEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTest()
  {
    return testEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTest_Name()
  {
    return (EAttribute)testEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTest_Description()
  {
    return (EAttribute)testEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTest_Statements()
  {
    return (EReference)testEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStatement()
  {
    return statementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getStatement_Body()
  {
    return (EReference)statementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGiven()
  {
    return givenEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getThen()
  {
    return thenEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWhen()
  {
    return whenEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStatementBody()
  {
    return statementBodyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSonarSent()
  {
    return sonarSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSonarSent_Sent()
  {
    return (EReference)sonarSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getNotificationSent()
  {
    return notificationSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getNotificationSent_Not()
  {
    return (EAttribute)notificationSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTimeSent()
  {
    return timeSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTimeInterval()
  {
    return timeIntervalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTimeInterval_First()
  {
    return (EReference)timeIntervalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTimeInterval_Second()
  {
    return (EReference)timeIntervalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBatterySent()
  {
    return batterySentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBatterySent_Sent()
  {
    return (EReference)batterySentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPeopleSent()
  {
    return peopleSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPeoplePosSent()
  {
    return peoplePosSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPeoplePosSent_PosX()
  {
    return (EAttribute)peoplePosSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPeoplePosSent_PosY()
  {
    return (EAttribute)peoplePosSentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPeoplePosSent_PosZ()
  {
    return (EAttribute)peoplePosSentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPeoplePosSent_Tolerance()
  {
    return (EReference)peoplePosSentEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPeopleNumbSent()
  {
    return peopleNumbSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPeopleNumbSent_Amount()
  {
    return (EAttribute)peopleNumbSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMissionSent()
  {
    return missionSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMissionGoalSent()
  {
    return missionGoalSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMissionGoalSent_PosX()
  {
    return (EAttribute)missionGoalSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMissionGoalSent_PosY()
  {
    return (EAttribute)missionGoalSentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMissionGoalSent_PosZ()
  {
    return (EAttribute)missionGoalSentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMissionRiskLevelSent()
  {
    return missionRiskLevelSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMissionRiskLevelSent_Risklevel()
  {
    return (EAttribute)missionRiskLevelSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMissionStatusSent()
  {
    return missionStatusSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMissionStatusSent_State()
  {
    return (EAttribute)missionStatusSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRobot()
  {
    return robotEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRobotAutoPilot()
  {
    return robotAutoPilotEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotAutoPilot_Status()
  {
    return (EAttribute)robotAutoPilotEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRedundantComponent()
  {
    return redundantComponentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRedundantComponent_Component()
  {
    return (EAttribute)redundantComponentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPayloadSent()
  {
    return payloadSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPayloadSent_Load()
  {
    return (EAttribute)payloadSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRobotDistanceSent()
  {
    return robotDistanceSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRobotDistanceSent_Sent()
  {
    return (EReference)robotDistanceSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDistanceToLocationSent()
  {
    return distanceToLocationSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDistanceToLocationSent_PosX()
  {
    return (EAttribute)distanceToLocationSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDistanceToLocationSent_PosY()
  {
    return (EAttribute)distanceToLocationSentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDistanceToLocationSent_PosZ()
  {
    return (EAttribute)distanceToLocationSentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDistanceToLocationSent_Body()
  {
    return (EReference)distanceToLocationSentEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDistanceToLocationSent_Tolerance()
  {
    return (EReference)distanceToLocationSentEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDistanceToObstaclesSent()
  {
    return distanceToObstaclesSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDistanceToObstaclesSent_Body()
  {
    return (EReference)distanceToObstaclesSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDistanceToObstaclesSent_Tolerance()
  {
    return (EReference)distanceToObstaclesSentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEqualSent()
  {
    return equalSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEqualSent_Amount()
  {
    return (EReference)equalSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLessSent()
  {
    return lessSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getLessSent_Amount()
  {
    return (EReference)lessSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGreaterSent()
  {
    return greaterSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGreaterSent_Amount()
  {
    return (EReference)greaterSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRobotStateSent()
  {
    return robotStateSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotStateSent_State()
  {
    return (EAttribute)robotStateSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRobotPositionSent()
  {
    return robotPositionSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotPositionSent_PosX()
  {
    return (EAttribute)robotPositionSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotPositionSent_PosY()
  {
    return (EAttribute)robotPositionSentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotPositionSent_PosZ()
  {
    return (EAttribute)robotPositionSentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRobotPositionSent_Tolerance()
  {
    return (EReference)robotPositionSentEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCirclePosition()
  {
    return circlePositionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCirclePosition_Tolerance()
  {
    return (EReference)circlePositionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSpherePosition()
  {
    return spherePositionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSpherePosition_Tolerance()
  {
    return (EReference)spherePositionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRobotSpeedSent()
  {
    return robotSpeedSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotSpeedSent_SpeedX()
  {
    return (EAttribute)robotSpeedSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotSpeedSent_SpeedY()
  {
    return (EAttribute)robotSpeedSentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRobotSpeedSent_SpeedZ()
  {
    return (EAttribute)robotSpeedSentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEnvironmentSent()
  {
    return environmentSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEnvironmentSent_Body()
  {
    return (EReference)environmentSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFailingComponentSent()
  {
    return failingComponentSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFailingComponentSent_Component()
  {
    return (EAttribute)failingComponentSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRiskSent()
  {
    return riskSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRiskSent_Level()
  {
    return (EAttribute)riskSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getToleranceSent()
  {
    return toleranceSentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getToleranceSent_Unit()
  {
    return (EReference)toleranceSentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDistanceUnit()
  {
    return distanceUnitEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDistanceUnit_Value()
  {
    return (EAttribute)distanceUnitEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTimeUnit()
  {
    return timeUnitEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTimeUnit_Value()
  {
    return (EAttribute)timeUnitEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSECONDS()
  {
    return secondsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getHOUR()
  {
    return hourEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMINUTES()
  {
    return minutesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMETER()
  {
    return meterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCENTIMETER()
  {
    return centimeterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMILLIMETER()
  {
    return millimeterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getKILOMETER()
  {
    return kilometerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPercentUnit()
  {
    return percentUnitEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPercentUnit_Value()
  {
    return (EAttribute)percentUnitEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyLanguageFactory getMyLanguageFactory()
  {
    return (MyLanguageFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    testFileEClass = createEClass(TEST_FILE);
    createEReference(testFileEClass, TEST_FILE__TESTS);

    testEClass = createEClass(TEST);
    createEAttribute(testEClass, TEST__NAME);
    createEAttribute(testEClass, TEST__DESCRIPTION);
    createEReference(testEClass, TEST__STATEMENTS);

    statementEClass = createEClass(STATEMENT);
    createEReference(statementEClass, STATEMENT__BODY);

    givenEClass = createEClass(GIVEN);

    thenEClass = createEClass(THEN);

    whenEClass = createEClass(WHEN);

    statementBodyEClass = createEClass(STATEMENT_BODY);

    sonarSentEClass = createEClass(SONAR_SENT);
    createEReference(sonarSentEClass, SONAR_SENT__SENT);

    notificationSentEClass = createEClass(NOTIFICATION_SENT);
    createEAttribute(notificationSentEClass, NOTIFICATION_SENT__NOT);

    timeSentEClass = createEClass(TIME_SENT);

    timeIntervalEClass = createEClass(TIME_INTERVAL);
    createEReference(timeIntervalEClass, TIME_INTERVAL__FIRST);
    createEReference(timeIntervalEClass, TIME_INTERVAL__SECOND);

    batterySentEClass = createEClass(BATTERY_SENT);
    createEReference(batterySentEClass, BATTERY_SENT__SENT);

    peopleSentEClass = createEClass(PEOPLE_SENT);

    peoplePosSentEClass = createEClass(PEOPLE_POS_SENT);
    createEAttribute(peoplePosSentEClass, PEOPLE_POS_SENT__POS_X);
    createEAttribute(peoplePosSentEClass, PEOPLE_POS_SENT__POS_Y);
    createEAttribute(peoplePosSentEClass, PEOPLE_POS_SENT__POS_Z);
    createEReference(peoplePosSentEClass, PEOPLE_POS_SENT__TOLERANCE);

    peopleNumbSentEClass = createEClass(PEOPLE_NUMB_SENT);
    createEAttribute(peopleNumbSentEClass, PEOPLE_NUMB_SENT__AMOUNT);

    missionSentEClass = createEClass(MISSION_SENT);

    missionGoalSentEClass = createEClass(MISSION_GOAL_SENT);
    createEAttribute(missionGoalSentEClass, MISSION_GOAL_SENT__POS_X);
    createEAttribute(missionGoalSentEClass, MISSION_GOAL_SENT__POS_Y);
    createEAttribute(missionGoalSentEClass, MISSION_GOAL_SENT__POS_Z);

    missionRiskLevelSentEClass = createEClass(MISSION_RISK_LEVEL_SENT);
    createEAttribute(missionRiskLevelSentEClass, MISSION_RISK_LEVEL_SENT__RISKLEVEL);

    missionStatusSentEClass = createEClass(MISSION_STATUS_SENT);
    createEAttribute(missionStatusSentEClass, MISSION_STATUS_SENT__STATE);

    robotEClass = createEClass(ROBOT);

    robotAutoPilotEClass = createEClass(ROBOT_AUTO_PILOT);
    createEAttribute(robotAutoPilotEClass, ROBOT_AUTO_PILOT__STATUS);

    redundantComponentEClass = createEClass(REDUNDANT_COMPONENT);
    createEAttribute(redundantComponentEClass, REDUNDANT_COMPONENT__COMPONENT);

    payloadSentEClass = createEClass(PAYLOAD_SENT);
    createEAttribute(payloadSentEClass, PAYLOAD_SENT__LOAD);

    robotDistanceSentEClass = createEClass(ROBOT_DISTANCE_SENT);
    createEReference(robotDistanceSentEClass, ROBOT_DISTANCE_SENT__SENT);

    distanceToLocationSentEClass = createEClass(DISTANCE_TO_LOCATION_SENT);
    createEAttribute(distanceToLocationSentEClass, DISTANCE_TO_LOCATION_SENT__POS_X);
    createEAttribute(distanceToLocationSentEClass, DISTANCE_TO_LOCATION_SENT__POS_Y);
    createEAttribute(distanceToLocationSentEClass, DISTANCE_TO_LOCATION_SENT__POS_Z);
    createEReference(distanceToLocationSentEClass, DISTANCE_TO_LOCATION_SENT__BODY);
    createEReference(distanceToLocationSentEClass, DISTANCE_TO_LOCATION_SENT__TOLERANCE);

    distanceToObstaclesSentEClass = createEClass(DISTANCE_TO_OBSTACLES_SENT);
    createEReference(distanceToObstaclesSentEClass, DISTANCE_TO_OBSTACLES_SENT__BODY);
    createEReference(distanceToObstaclesSentEClass, DISTANCE_TO_OBSTACLES_SENT__TOLERANCE);

    equalSentEClass = createEClass(EQUAL_SENT);
    createEReference(equalSentEClass, EQUAL_SENT__AMOUNT);

    lessSentEClass = createEClass(LESS_SENT);
    createEReference(lessSentEClass, LESS_SENT__AMOUNT);

    greaterSentEClass = createEClass(GREATER_SENT);
    createEReference(greaterSentEClass, GREATER_SENT__AMOUNT);

    robotStateSentEClass = createEClass(ROBOT_STATE_SENT);
    createEAttribute(robotStateSentEClass, ROBOT_STATE_SENT__STATE);

    robotPositionSentEClass = createEClass(ROBOT_POSITION_SENT);
    createEAttribute(robotPositionSentEClass, ROBOT_POSITION_SENT__POS_X);
    createEAttribute(robotPositionSentEClass, ROBOT_POSITION_SENT__POS_Y);
    createEAttribute(robotPositionSentEClass, ROBOT_POSITION_SENT__POS_Z);
    createEReference(robotPositionSentEClass, ROBOT_POSITION_SENT__TOLERANCE);

    circlePositionEClass = createEClass(CIRCLE_POSITION);
    createEReference(circlePositionEClass, CIRCLE_POSITION__TOLERANCE);

    spherePositionEClass = createEClass(SPHERE_POSITION);
    createEReference(spherePositionEClass, SPHERE_POSITION__TOLERANCE);

    robotSpeedSentEClass = createEClass(ROBOT_SPEED_SENT);
    createEAttribute(robotSpeedSentEClass, ROBOT_SPEED_SENT__SPEED_X);
    createEAttribute(robotSpeedSentEClass, ROBOT_SPEED_SENT__SPEED_Y);
    createEAttribute(robotSpeedSentEClass, ROBOT_SPEED_SENT__SPEED_Z);

    environmentSentEClass = createEClass(ENVIRONMENT_SENT);
    createEReference(environmentSentEClass, ENVIRONMENT_SENT__BODY);

    failingComponentSentEClass = createEClass(FAILING_COMPONENT_SENT);
    createEAttribute(failingComponentSentEClass, FAILING_COMPONENT_SENT__COMPONENT);

    riskSentEClass = createEClass(RISK_SENT);
    createEAttribute(riskSentEClass, RISK_SENT__LEVEL);

    toleranceSentEClass = createEClass(TOLERANCE_SENT);
    createEReference(toleranceSentEClass, TOLERANCE_SENT__UNIT);

    distanceUnitEClass = createEClass(DISTANCE_UNIT);
    createEAttribute(distanceUnitEClass, DISTANCE_UNIT__VALUE);

    timeUnitEClass = createEClass(TIME_UNIT);
    createEAttribute(timeUnitEClass, TIME_UNIT__VALUE);

    secondsEClass = createEClass(SECONDS);

    hourEClass = createEClass(HOUR);

    minutesEClass = createEClass(MINUTES);

    meterEClass = createEClass(METER);

    centimeterEClass = createEClass(CENTIMETER);

    millimeterEClass = createEClass(MILLIMETER);

    kilometerEClass = createEClass(KILOMETER);

    percentUnitEClass = createEClass(PERCENT_UNIT);
    createEAttribute(percentUnitEClass, PERCENT_UNIT__VALUE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    givenEClass.getESuperTypes().add(this.getStatement());
    thenEClass.getESuperTypes().add(this.getStatement());
    whenEClass.getESuperTypes().add(this.getStatement());
    sonarSentEClass.getESuperTypes().add(this.getStatementBody());
    notificationSentEClass.getESuperTypes().add(this.getStatementBody());
    timeSentEClass.getESuperTypes().add(this.getStatementBody());
    timeIntervalEClass.getESuperTypes().add(this.getTimeSent());
    batterySentEClass.getESuperTypes().add(this.getStatementBody());
    peopleSentEClass.getESuperTypes().add(this.getStatementBody());
    peoplePosSentEClass.getESuperTypes().add(this.getPeopleSent());
    peopleNumbSentEClass.getESuperTypes().add(this.getPeopleSent());
    missionSentEClass.getESuperTypes().add(this.getStatementBody());
    missionGoalSentEClass.getESuperTypes().add(this.getMissionSent());
    missionRiskLevelSentEClass.getESuperTypes().add(this.getMissionSent());
    missionStatusSentEClass.getESuperTypes().add(this.getMissionSent());
    robotEClass.getESuperTypes().add(this.getStatementBody());
    robotAutoPilotEClass.getESuperTypes().add(this.getRobot());
    redundantComponentEClass.getESuperTypes().add(this.getRobot());
    payloadSentEClass.getESuperTypes().add(this.getRobot());
    robotDistanceSentEClass.getESuperTypes().add(this.getRobot());
    robotStateSentEClass.getESuperTypes().add(this.getRobot());
    robotPositionSentEClass.getESuperTypes().add(this.getRobot());
    robotSpeedSentEClass.getESuperTypes().add(this.getRobot());
    environmentSentEClass.getESuperTypes().add(this.getStatementBody());
    failingComponentSentEClass.getESuperTypes().add(this.getRobot());
    riskSentEClass.getESuperTypes().add(this.getRobot());
    secondsEClass.getESuperTypes().add(this.getTimeUnit());
    hourEClass.getESuperTypes().add(this.getTimeUnit());
    minutesEClass.getESuperTypes().add(this.getTimeUnit());
    meterEClass.getESuperTypes().add(this.getDistanceUnit());
    centimeterEClass.getESuperTypes().add(this.getDistanceUnit());
    millimeterEClass.getESuperTypes().add(this.getDistanceUnit());
    kilometerEClass.getESuperTypes().add(this.getDistanceUnit());

    // Initialize classes and features; add operations and parameters
    initEClass(testFileEClass, TestFile.class, "TestFile", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTestFile_Tests(), this.getTest(), null, "tests", null, 0, -1, TestFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(testEClass, Test.class, "Test", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTest_Name(), ecorePackage.getEString(), "name", null, 0, 1, Test.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTest_Description(), ecorePackage.getEString(), "description", null, 0, 1, Test.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTest_Statements(), this.getStatement(), null, "statements", null, 0, -1, Test.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(statementEClass, Statement.class, "Statement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStatement_Body(), this.getStatementBody(), null, "body", null, 0, 1, Statement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(givenEClass, Given.class, "Given", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(thenEClass, Then.class, "Then", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(whenEClass, When.class, "When", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(statementBodyEClass, StatementBody.class, "StatementBody", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(sonarSentEClass, SonarSent.class, "SonarSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSonarSent_Sent(), ecorePackage.getEObject(), null, "sent", null, 0, 1, SonarSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(notificationSentEClass, NotificationSent.class, "NotificationSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNotificationSent_Not(), ecorePackage.getEString(), "not", null, 0, 1, NotificationSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(timeSentEClass, TimeSent.class, "TimeSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(timeIntervalEClass, TimeInterval.class, "TimeInterval", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTimeInterval_First(), this.getTimeUnit(), null, "first", null, 0, 1, TimeInterval.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTimeInterval_Second(), this.getTimeUnit(), null, "second", null, 0, 1, TimeInterval.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(batterySentEClass, BatterySent.class, "BatterySent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBatterySent_Sent(), ecorePackage.getEObject(), null, "sent", null, 0, 1, BatterySent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(peopleSentEClass, PeopleSent.class, "PeopleSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(peoplePosSentEClass, PeoplePosSent.class, "PeoplePosSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPeoplePosSent_PosX(), ecorePackage.getEString(), "posX", null, 0, 1, PeoplePosSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPeoplePosSent_PosY(), ecorePackage.getEString(), "posY", null, 0, 1, PeoplePosSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPeoplePosSent_PosZ(), ecorePackage.getEString(), "posZ", null, 0, 1, PeoplePosSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPeoplePosSent_Tolerance(), ecorePackage.getEObject(), null, "tolerance", null, 0, 1, PeoplePosSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(peopleNumbSentEClass, PeopleNumbSent.class, "PeopleNumbSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPeopleNumbSent_Amount(), ecorePackage.getEInt(), "amount", null, 0, 1, PeopleNumbSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(missionSentEClass, MissionSent.class, "MissionSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(missionGoalSentEClass, MissionGoalSent.class, "MissionGoalSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMissionGoalSent_PosX(), ecorePackage.getEString(), "posX", null, 0, 1, MissionGoalSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMissionGoalSent_PosY(), ecorePackage.getEString(), "posY", null, 0, 1, MissionGoalSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMissionGoalSent_PosZ(), ecorePackage.getEString(), "posZ", null, 0, 1, MissionGoalSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(missionRiskLevelSentEClass, MissionRiskLevelSent.class, "MissionRiskLevelSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMissionRiskLevelSent_Risklevel(), ecorePackage.getEString(), "risklevel", null, 0, 1, MissionRiskLevelSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(missionStatusSentEClass, MissionStatusSent.class, "MissionStatusSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMissionStatusSent_State(), ecorePackage.getEString(), "state", null, 0, 1, MissionStatusSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(robotEClass, Robot.class, "Robot", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(robotAutoPilotEClass, RobotAutoPilot.class, "RobotAutoPilot", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRobotAutoPilot_Status(), ecorePackage.getEString(), "status", null, 0, 1, RobotAutoPilot.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(redundantComponentEClass, RedundantComponent.class, "RedundantComponent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRedundantComponent_Component(), ecorePackage.getEString(), "component", null, 0, 1, RedundantComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(payloadSentEClass, PayloadSent.class, "PayloadSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPayloadSent_Load(), ecorePackage.getEString(), "load", null, 0, 1, PayloadSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(robotDistanceSentEClass, RobotDistanceSent.class, "RobotDistanceSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRobotDistanceSent_Sent(), ecorePackage.getEObject(), null, "sent", null, 0, 1, RobotDistanceSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(distanceToLocationSentEClass, DistanceToLocationSent.class, "DistanceToLocationSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDistanceToLocationSent_PosX(), ecorePackage.getEString(), "posX", null, 0, 1, DistanceToLocationSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDistanceToLocationSent_PosY(), ecorePackage.getEString(), "posY", null, 0, 1, DistanceToLocationSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDistanceToLocationSent_PosZ(), ecorePackage.getEString(), "posZ", null, 0, 1, DistanceToLocationSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDistanceToLocationSent_Body(), ecorePackage.getEObject(), null, "body", null, 0, 1, DistanceToLocationSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDistanceToLocationSent_Tolerance(), this.getToleranceSent(), null, "tolerance", null, 0, 1, DistanceToLocationSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(distanceToObstaclesSentEClass, DistanceToObstaclesSent.class, "DistanceToObstaclesSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDistanceToObstaclesSent_Body(), ecorePackage.getEObject(), null, "body", null, 0, 1, DistanceToObstaclesSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDistanceToObstaclesSent_Tolerance(), this.getToleranceSent(), null, "tolerance", null, 0, 1, DistanceToObstaclesSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(equalSentEClass, EqualSent.class, "EqualSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEqualSent_Amount(), ecorePackage.getEObject(), null, "amount", null, 0, 1, EqualSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lessSentEClass, LessSent.class, "LessSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLessSent_Amount(), ecorePackage.getEObject(), null, "amount", null, 0, 1, LessSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(greaterSentEClass, GreaterSent.class, "GreaterSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGreaterSent_Amount(), ecorePackage.getEObject(), null, "amount", null, 0, 1, GreaterSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(robotStateSentEClass, RobotStateSent.class, "RobotStateSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRobotStateSent_State(), ecorePackage.getEString(), "state", null, 0, 1, RobotStateSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(robotPositionSentEClass, RobotPositionSent.class, "RobotPositionSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRobotPositionSent_PosX(), ecorePackage.getEString(), "posX", null, 0, 1, RobotPositionSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRobotPositionSent_PosY(), ecorePackage.getEString(), "posY", null, 0, 1, RobotPositionSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRobotPositionSent_PosZ(), ecorePackage.getEString(), "posZ", null, 0, 1, RobotPositionSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRobotPositionSent_Tolerance(), ecorePackage.getEObject(), null, "tolerance", null, 0, 1, RobotPositionSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(circlePositionEClass, CirclePosition.class, "CirclePosition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCirclePosition_Tolerance(), this.getDistanceUnit(), null, "tolerance", null, 0, 1, CirclePosition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(spherePositionEClass, SpherePosition.class, "SpherePosition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSpherePosition_Tolerance(), this.getDistanceUnit(), null, "tolerance", null, 0, 1, SpherePosition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(robotSpeedSentEClass, RobotSpeedSent.class, "RobotSpeedSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRobotSpeedSent_SpeedX(), ecorePackage.getEString(), "speedX", null, 0, 1, RobotSpeedSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRobotSpeedSent_SpeedY(), ecorePackage.getEString(), "speedY", null, 0, 1, RobotSpeedSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRobotSpeedSent_SpeedZ(), ecorePackage.getEString(), "speedZ", null, 0, 1, RobotSpeedSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(environmentSentEClass, EnvironmentSent.class, "EnvironmentSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEnvironmentSent_Body(), ecorePackage.getEObject(), null, "body", null, 0, 1, EnvironmentSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(failingComponentSentEClass, FailingComponentSent.class, "FailingComponentSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFailingComponentSent_Component(), ecorePackage.getEString(), "component", null, 0, 1, FailingComponentSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(riskSentEClass, RiskSent.class, "RiskSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRiskSent_Level(), ecorePackage.getEString(), "level", null, 0, 1, RiskSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(toleranceSentEClass, ToleranceSent.class, "ToleranceSent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getToleranceSent_Unit(), this.getDistanceUnit(), null, "unit", null, 0, 1, ToleranceSent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(distanceUnitEClass, DistanceUnit.class, "DistanceUnit", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDistanceUnit_Value(), ecorePackage.getEString(), "value", null, 0, 1, DistanceUnit.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(timeUnitEClass, TimeUnit.class, "TimeUnit", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTimeUnit_Value(), ecorePackage.getEString(), "value", null, 0, 1, TimeUnit.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(secondsEClass, org.xtext.example.mydsl.myLanguage.SECONDS.class, "SECONDS", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(hourEClass, org.xtext.example.mydsl.myLanguage.HOUR.class, "HOUR", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(minutesEClass, org.xtext.example.mydsl.myLanguage.MINUTES.class, "MINUTES", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(meterEClass, org.xtext.example.mydsl.myLanguage.METER.class, "METER", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(centimeterEClass, org.xtext.example.mydsl.myLanguage.CENTIMETER.class, "CENTIMETER", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(millimeterEClass, org.xtext.example.mydsl.myLanguage.MILLIMETER.class, "MILLIMETER", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(kilometerEClass, org.xtext.example.mydsl.myLanguage.KILOMETER.class, "KILOMETER", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(percentUnitEClass, PercentUnit.class, "PercentUnit", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPercentUnit_Value(), ecorePackage.getEString(), "value", null, 0, 1, PercentUnit.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //MyLanguagePackageImpl
