/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myLanguage.MyLanguagePackage;
import org.xtext.example.mydsl.myLanguage.PeopleSent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>People Sent</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PeopleSentImpl extends StatementBodyImpl implements PeopleSent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PeopleSentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyLanguagePackage.Literals.PEOPLE_SENT;
  }

} //PeopleSentImpl
