/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myLanguage.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myLanguage.MyLanguagePackage;
import org.xtext.example.mydsl.myLanguage.PeoplePosSent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>People Pos Sent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.impl.PeoplePosSentImpl#getPosX <em>Pos X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.impl.PeoplePosSentImpl#getPosY <em>Pos Y</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.impl.PeoplePosSentImpl#getPosZ <em>Pos Z</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myLanguage.impl.PeoplePosSentImpl#getTolerance <em>Tolerance</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PeoplePosSentImpl extends PeopleSentImpl implements PeoplePosSent
{
  /**
   * The default value of the '{@link #getPosX() <em>Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosX()
   * @generated
   * @ordered
   */
  protected static final String POS_X_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPosX() <em>Pos X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosX()
   * @generated
   * @ordered
   */
  protected String posX = POS_X_EDEFAULT;

  /**
   * The default value of the '{@link #getPosY() <em>Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosY()
   * @generated
   * @ordered
   */
  protected static final String POS_Y_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPosY() <em>Pos Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosY()
   * @generated
   * @ordered
   */
  protected String posY = POS_Y_EDEFAULT;

  /**
   * The default value of the '{@link #getPosZ() <em>Pos Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosZ()
   * @generated
   * @ordered
   */
  protected static final String POS_Z_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPosZ() <em>Pos Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosZ()
   * @generated
   * @ordered
   */
  protected String posZ = POS_Z_EDEFAULT;

  /**
   * The cached value of the '{@link #getTolerance() <em>Tolerance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTolerance()
   * @generated
   * @ordered
   */
  protected EObject tolerance;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PeoplePosSentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyLanguagePackage.Literals.PEOPLE_POS_SENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPosX()
  {
    return posX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPosX(String newPosX)
  {
    String oldPosX = posX;
    posX = newPosX;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyLanguagePackage.PEOPLE_POS_SENT__POS_X, oldPosX, posX));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPosY()
  {
    return posY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPosY(String newPosY)
  {
    String oldPosY = posY;
    posY = newPosY;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyLanguagePackage.PEOPLE_POS_SENT__POS_Y, oldPosY, posY));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPosZ()
  {
    return posZ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPosZ(String newPosZ)
  {
    String oldPosZ = posZ;
    posZ = newPosZ;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyLanguagePackage.PEOPLE_POS_SENT__POS_Z, oldPosZ, posZ));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getTolerance()
  {
    return tolerance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTolerance(EObject newTolerance, NotificationChain msgs)
  {
    EObject oldTolerance = tolerance;
    tolerance = newTolerance;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE, oldTolerance, newTolerance);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTolerance(EObject newTolerance)
  {
    if (newTolerance != tolerance)
    {
      NotificationChain msgs = null;
      if (tolerance != null)
        msgs = ((InternalEObject)tolerance).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE, null, msgs);
      if (newTolerance != null)
        msgs = ((InternalEObject)newTolerance).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE, null, msgs);
      msgs = basicSetTolerance(newTolerance, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE, newTolerance, newTolerance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE:
        return basicSetTolerance(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_X:
        return getPosX();
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Y:
        return getPosY();
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Z:
        return getPosZ();
      case MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE:
        return getTolerance();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_X:
        setPosX((String)newValue);
        return;
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Y:
        setPosY((String)newValue);
        return;
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Z:
        setPosZ((String)newValue);
        return;
      case MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE:
        setTolerance((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_X:
        setPosX(POS_X_EDEFAULT);
        return;
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Y:
        setPosY(POS_Y_EDEFAULT);
        return;
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Z:
        setPosZ(POS_Z_EDEFAULT);
        return;
      case MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE:
        setTolerance((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_X:
        return POS_X_EDEFAULT == null ? posX != null : !POS_X_EDEFAULT.equals(posX);
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Y:
        return POS_Y_EDEFAULT == null ? posY != null : !POS_Y_EDEFAULT.equals(posY);
      case MyLanguagePackage.PEOPLE_POS_SENT__POS_Z:
        return POS_Z_EDEFAULT == null ? posZ != null : !POS_Z_EDEFAULT.equals(posZ);
      case MyLanguagePackage.PEOPLE_POS_SENT__TOLERANCE:
        return tolerance != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (posX: ");
    result.append(posX);
    result.append(", posY: ");
    result.append(posY);
    result.append(", posZ: ");
    result.append(posZ);
    result.append(')');
    return result.toString();
  }

} //PeoplePosSentImpl
