/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.example.mydsl.myLanguage.TestFile

@RunWith(XtextRunner)
@InjectWith(MyLanguageInjectorProvider)
class MyLanguageParsingTest{

	@Inject
	ParseHelper<TestFile> parseHelper

	@Test 
	def void loadModel() {
		Assert.assertNotNull(1)
	}

}
