/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myLanguage.BaroSent;
import org.xtext.example.mydsl.myLanguage.BatterySent;
import org.xtext.example.mydsl.myLanguage.CENTIMETER;
import org.xtext.example.mydsl.myLanguage.CirclePosition;
import org.xtext.example.mydsl.myLanguage.DistanceToLocationSent;
import org.xtext.example.mydsl.myLanguage.DistanceToObstaclesSent;
import org.xtext.example.mydsl.myLanguage.DistanceUnit;
import org.xtext.example.mydsl.myLanguage.EnvironmentSent;
import org.xtext.example.mydsl.myLanguage.EqualSent;
import org.xtext.example.mydsl.myLanguage.Given;
import org.xtext.example.mydsl.myLanguage.GreaterSent;
import org.xtext.example.mydsl.myLanguage.HOUR;
import org.xtext.example.mydsl.myLanguage.KILOMETER;
import org.xtext.example.mydsl.myLanguage.LessSent;
import org.xtext.example.mydsl.myLanguage.METER;
import org.xtext.example.mydsl.myLanguage.MILLIMETER;
import org.xtext.example.mydsl.myLanguage.MINUTES;
import org.xtext.example.mydsl.myLanguage.MissionGoalSent;
import org.xtext.example.mydsl.myLanguage.MissionRiskLevelSent;
import org.xtext.example.mydsl.myLanguage.MissionStatusSent;
import org.xtext.example.mydsl.myLanguage.PercentUnit;
import org.xtext.example.mydsl.myLanguage.RobotDistanceSent;
import org.xtext.example.mydsl.myLanguage.RobotPositionSent;
import org.xtext.example.mydsl.myLanguage.RobotSpeedSent;
import org.xtext.example.mydsl.myLanguage.RobotStateSent;
import org.xtext.example.mydsl.myLanguage.SECONDS;
import org.xtext.example.mydsl.myLanguage.SonarSent;
import org.xtext.example.mydsl.myLanguage.SpherePosition;
import org.xtext.example.mydsl.myLanguage.Statement;
import org.xtext.example.mydsl.myLanguage.StatementBody;
import org.xtext.example.mydsl.myLanguage.Test;
import org.xtext.example.mydsl.myLanguage.TestFile;
import org.xtext.example.mydsl.myLanguage.Then;
import org.xtext.example.mydsl.myLanguage.TimeInterval;
import org.xtext.example.mydsl.myLanguage.TimeUnit;
import org.xtext.example.mydsl.myLanguage.When;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyLanguageGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    String _string = resource.toString();
    String[] _split = _string.split("\\.");
    String _string_1 = resource.toString();
    String[] _split_1 = _string_1.split("\\.");
    int _length = _split_1.length;
    int _minus = (_length - 2);
    String _get = _split[_minus];
    String name = _get.replaceAll("[^A-Za-z0-9]", "");
    int index = name.indexOf("javafeatures");
    String _substring = name.substring((index + 12));
    name = _substring;
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<TestFile> _filter = Iterables.<TestFile>filter(_iterable, TestFile.class);
    for (final TestFile e : _filter) {
      CharSequence _compile = this.compile(e, name);
      fsa.generateFile((name + ".java"), _compile);
    }
  }
  
  public CharSequence compile(final TestFile f, final String name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package features;");
    _builder.newLine();
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import com.github.drone.subb.Application;");
    _builder.newLine();
    _builder.append("import com.github.drone.subb.IDrone;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import SimpleTester.*;");
    _builder.newLine();
    _builder.append("import Units.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(name, "");
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private List<Test> tests = new ArrayList<Test>();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private IDrone drone = null;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Application app = null;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(name, "\t");
    _builder.append("(IDrone drone, Application app){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.drone = drone;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.app = app;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<Statement> stat = new ArrayList<Statement>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Test test;");
    _builder.newLine();
    {
      EList<Test> _tests = f.getTests();
      for(final Test t : _tests) {
        _builder.append("\t\t");
        _builder.append("stat = new ArrayList<Statement>();");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("test = new Test(\"");
        String _name = t.getName();
        _builder.append(_name, "\t\t");
        _builder.append("\",\"");
        String _description = t.getDescription();
        _builder.append(_description, "\t\t");
        _builder.append("\", this.app);");
        _builder.newLineIfNotEmpty();
        {
          EList<Statement> _statements = t.getStatements();
          for(final Statement s : _statements) {
            _builder.append("\t\t");
            _builder.append("stat.add(");
            CharSequence _createStatement = this.createStatement(s);
            _builder.append(_createStatement, "\t\t");
            _builder.append(");");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t\t");
        _builder.append("test.commitStatements(stat);");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("this.tests.add(test);");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<Test> getTests(){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.tests;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void run(){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ArrayList<Thread> threads = new ArrayList<Thread>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for( Test t: this.getTests()){");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Thread th = new Thread(t);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("th.start();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("threads.add(th);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for(int i = 0; i < threads.size(); i++)");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("threads.get(i).join();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence createStatement(final Statement obj) {
    CharSequence _switchResult = null;
    boolean _matched = false;
    if (obj instanceof Given) {
      if ((obj instanceof Given)) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("new GivenStatement(");
        CharSequence _createBody = this.createBody(obj);
        _builder.append(_createBody, "");
        _builder.append(")");
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (obj instanceof Then) {
        if ((obj instanceof Then)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new ThenStatement(");
          CharSequence _createBody = this.createBody(obj);
          _builder.append(_createBody, "");
          _builder.append(")");
          _switchResult = _builder;
        }
      }
    }
    if (!_matched) {
      if (obj instanceof When) {
        if ((obj instanceof When)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new WhenStatement(");
          CharSequence _createBody = this.createBody(obj);
          _builder.append(_createBody, "");
          _builder.append(")");
          _switchResult = _builder;
        }
      }
    }
    if (!_matched) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("new Statement(\"\")");
      _switchResult = _builder;
    }
    return _switchResult;
  }
  
  public CharSequence createBody(final Statement obj) {
    CharSequence _xblockexpression = null;
    {
      StatementBody bod = obj.getBody();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (bod instanceof RobotPositionSent) {
        if ((bod instanceof RobotPositionSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          CharSequence _createRunStat = this.createRunStat(((RobotPositionSent)bod));
          _builder.append(_createRunStat, "");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (bod instanceof RobotSpeedSent) {
          if ((bod instanceof RobotSpeedSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((RobotSpeedSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof EnvironmentSent) {
          if ((bod instanceof EnvironmentSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((EnvironmentSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof RobotStateSent) {
          if ((bod instanceof RobotStateSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((RobotStateSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof RobotDistanceSent) {
          if ((bod instanceof RobotDistanceSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((RobotDistanceSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof BatterySent) {
          if ((bod instanceof BatterySent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((BatterySent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof SonarSent) {
          if ((bod instanceof SonarSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((SonarSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof BaroSent) {
          if ((bod instanceof BaroSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((BaroSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof MissionGoalSent) {
          if ((bod instanceof MissionGoalSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((MissionGoalSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof MissionRiskLevelSent) {
          if ((bod instanceof MissionRiskLevelSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((MissionRiskLevelSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof MissionStatusSent) {
          if ((bod instanceof MissionStatusSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((MissionStatusSent)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (bod instanceof TimeInterval) {
          if ((bod instanceof TimeInterval)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((TimeInterval)bod));
            _builder.append(_createRunStat, "");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final RobotPositionSent body) {
    CharSequence _xblockexpression = null;
    {
      EObject tolerance = body.getTolerance();
      CharSequence _xifexpression = null;
      boolean _equals = Objects.equal(tolerance, null);
      if (_equals) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("new RobotPosSentence(");
        String _posX = body.getPosX();
        _builder.append(_posX, "");
        _builder.append(", ");
        String _posY = body.getPosY();
        _builder.append(_posY, "");
        _builder.append(" , ");
        String _posZ = body.getPosZ();
        _builder.append(_posZ, "");
        _builder.append(", new SpherePosition(new Meter(0)), this.app , this.drone)");
        _xifexpression = _builder;
      } else {
        CharSequence _xblockexpression_1 = null;
        {
          EObject sent = body.getTolerance();
          CharSequence _switchResult = null;
          boolean _matched = false;
          if (sent instanceof CirclePosition) {
            if ((sent instanceof CirclePosition)) {
              _matched=true;
              StringConcatenation _builder_1 = new StringConcatenation();
              _builder_1.append("new RobotPosSentence(");
              String _posX_1 = body.getPosX();
              _builder_1.append(_posX_1, "");
              _builder_1.append(", ");
              String _posY_1 = body.getPosY();
              _builder_1.append(_posY_1, "");
              _builder_1.append(" , ");
              String _posZ_1 = body.getPosZ();
              _builder_1.append(_posZ_1, "");
              _builder_1.append(", ");
              CharSequence _createRunStat = this.createRunStat(((CirclePosition)sent));
              _builder_1.append(_createRunStat, "");
              _builder_1.append(", this.app, this.drone)");
              _switchResult = _builder_1;
            }
          }
          if (!_matched) {
            if (sent instanceof SpherePosition) {
              if ((sent instanceof SpherePosition)) {
                _matched=true;
                StringConcatenation _builder_1 = new StringConcatenation();
                _builder_1.append("new RobotPosSentence(");
                String _posX_1 = body.getPosX();
                _builder_1.append(_posX_1, "");
                _builder_1.append(", ");
                String _posY_1 = body.getPosY();
                _builder_1.append(_posY_1, "");
                _builder_1.append(" , ");
                String _posZ_1 = body.getPosZ();
                _builder_1.append(_posZ_1, "");
                _builder_1.append(", ");
                CharSequence _createRunStat = this.createRunStat(((SpherePosition)sent));
                _builder_1.append(_createRunStat, "");
                _builder_1.append(", this.app, this.drone)");
                _switchResult = _builder_1;
              }
            }
          }
          _xblockexpression_1 = _switchResult;
        }
        _xifexpression = _xblockexpression_1;
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final CirclePosition sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new CirclePosition(");
    DistanceUnit _tolerance = sent.getTolerance();
    CharSequence _createRunStat = this.createRunStat(_tolerance);
    _builder.append(_createRunStat, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final SpherePosition sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new SpherePosition(");
    DistanceUnit _tolerance = sent.getTolerance();
    CharSequence _createRunStat = this.createRunStat(_tolerance);
    _builder.append(_createRunStat, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final RobotSpeedSent body) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new RobotSpdSentence(");
    String _speedX = body.getSpeedX();
    _builder.append(_speedX, "");
    _builder.append(", ");
    String _speedY = body.getSpeedY();
    _builder.append(_speedY, "");
    _builder.append(" , ");
    String _speedZ = body.getSpeedZ();
    _builder.append(_speedZ, "");
    _builder.append(", this.app, this.drone)");
    return _builder;
  }
  
  public CharSequence createRunStat(final RobotStateSent body) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new RobotStSentence(\"");
    String _state = body.getState();
    _builder.append(_state, "");
    _builder.append("\", this.app, this.drone)");
    return _builder;
  }
  
  public CharSequence createRunStat(final RobotDistanceSent body) {
    CharSequence _xblockexpression = null;
    {
      EObject sent = body.getSent();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (sent instanceof DistanceToLocationSent) {
        if ((sent instanceof DistanceToLocationSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new RobotDistSentence(");
          CharSequence _createRunStat = this.createRunStat(((DistanceToLocationSent)sent));
          _builder.append(_createRunStat, "");
          _builder.append(")");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (sent instanceof DistanceToObstaclesSent) {
          if ((sent instanceof DistanceToObstaclesSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new RobotDistToObsSentence(");
            CharSequence _createRunStat = this.createRunStat(((DistanceToObstaclesSent)sent));
            _builder.append(_createRunStat, "");
            _builder.append(")");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("foutje");
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final DistanceToLocationSent sent) {
    CharSequence _xblockexpression = null;
    {
      EObject body = sent.getBody();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (body instanceof EqualSent) {
        if ((body instanceof EqualSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new DistanceToLocSentence(");
          String _posX = sent.getPosX();
          _builder.append(_posX, "");
          _builder.append(", ");
          String _posY = sent.getPosY();
          _builder.append(_posY, "");
          _builder.append(", ");
          String _posZ = sent.getPosZ();
          _builder.append(_posZ, "");
          _builder.append(",");
          CharSequence _createRunStat = this.createRunStat(((EqualSent)body));
          _builder.append(_createRunStat, "");
          _builder.append(" , this.app, this.drone)");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (body instanceof GreaterSent) {
          if ((body instanceof GreaterSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new DistanceToLocSentence(");
            String _posX = sent.getPosX();
            _builder.append(_posX, "");
            _builder.append(", ");
            String _posY = sent.getPosY();
            _builder.append(_posY, "");
            _builder.append(", ");
            String _posZ = sent.getPosZ();
            _builder.append(_posZ, "");
            _builder.append(",");
            CharSequence _createRunStat = this.createRunStat(((GreaterSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (body instanceof LessSent) {
          if ((body instanceof LessSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new DistanceToLocSentence(");
            String _posX = sent.getPosX();
            _builder.append(_posX, "");
            _builder.append(", ");
            String _posY = sent.getPosY();
            _builder.append(_posY, "");
            _builder.append(", ");
            String _posZ = sent.getPosZ();
            _builder.append(_posZ, "");
            _builder.append(",");
            CharSequence _createRunStat = this.createRunStat(((LessSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("foutje");
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final DistanceToObstaclesSent sent) {
    CharSequence _xblockexpression = null;
    {
      EObject body = sent.getBody();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (body instanceof EqualSent) {
        if ((body instanceof EqualSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          CharSequence _createRunStat = this.createRunStat(((EqualSent)body));
          _builder.append(_createRunStat, "");
          _builder.append(", this.app, this.drone");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (body instanceof GreaterSent) {
          if ((body instanceof GreaterSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((GreaterSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(", this.app, this.drone");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (body instanceof LessSent) {
          if ((body instanceof LessSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            CharSequence _createRunStat = this.createRunStat(((LessSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(", this.app, this.drone");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("foutje");
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final EqualSent sent) {
    CharSequence _xblockexpression = null;
    {
      EObject amount = sent.getAmount();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (amount instanceof DistanceUnit) {
        if ((amount instanceof DistanceUnit)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new EqualSentence(");
          CharSequence _createRunStat = this.createRunStat(((DistanceUnit)amount));
          _builder.append(_createRunStat, "");
          _builder.append(")");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (amount instanceof PercentUnit) {
          if ((amount instanceof PercentUnit)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new EqualSentence(");
            CharSequence _createRunStat = this.createRunStat(((PercentUnit)amount));
            _builder.append(_createRunStat, "");
            _builder.append(")");
            _switchResult = _builder;
          }
        }
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final GreaterSent sent) {
    CharSequence _xblockexpression = null;
    {
      EObject amount = sent.getAmount();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (amount instanceof DistanceUnit) {
        if ((amount instanceof DistanceUnit)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new GreaterSentence(");
          CharSequence _createRunStat = this.createRunStat(((DistanceUnit)amount));
          _builder.append(_createRunStat, "");
          _builder.append(")");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (amount instanceof PercentUnit) {
          if ((amount instanceof PercentUnit)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new GreaterSentence(");
            CharSequence _createRunStat = this.createRunStat(((PercentUnit)amount));
            _builder.append(_createRunStat, "");
            _builder.append(")");
            _switchResult = _builder;
          }
        }
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final LessSent sent) {
    CharSequence _xblockexpression = null;
    {
      EObject amount = sent.getAmount();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (amount instanceof DistanceUnit) {
        if ((amount instanceof DistanceUnit)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new LessSentence(");
          CharSequence _createRunStat = this.createRunStat(((DistanceUnit)amount));
          _builder.append(_createRunStat, "");
          _builder.append(")");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (amount instanceof PercentUnit) {
          if ((amount instanceof PercentUnit)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new LessSentence(");
            CharSequence _createRunStat = this.createRunStat(((PercentUnit)amount));
            _builder.append(_createRunStat, "");
            _builder.append(")");
            _switchResult = _builder;
          }
        }
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final MissionGoalSent sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new MissionGoalSentence(");
    String _posX = sent.getPosX();
    _builder.append(_posX, "");
    _builder.append(", ");
    String _posY = sent.getPosY();
    _builder.append(_posY, "");
    _builder.append(", ");
    String _posZ = sent.getPosZ();
    _builder.append(_posZ, "");
    _builder.append(", this.app, this.drone)");
    return _builder;
  }
  
  public CharSequence createRunStat(final MissionRiskLevelSent sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new MissionRiskLevelSentence(\"");
    String _risklevel = sent.getRisklevel();
    _builder.append(_risklevel, "");
    _builder.append("\"\", this.app, this.drone)");
    return _builder;
  }
  
  public CharSequence createRunStat(final MissionStatusSent sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new MissionStatusSentence(\"");
    String _state = sent.getState();
    _builder.append(_state, "");
    _builder.append("\", this.app, this.drone)");
    return _builder;
  }
  
  public CharSequence createRunStat(final TimeInterval sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new timeIntervalSentence(");
    TimeUnit _first = sent.getFirst();
    CharSequence _createRunStat = this.createRunStat(_first);
    _builder.append(_createRunStat, "");
    _builder.append(", ");
    TimeUnit _second = sent.getSecond();
    CharSequence _createRunStat_1 = this.createRunStat(_second);
    _builder.append(_createRunStat_1, "");
    _builder.append(", this.app, this.drone, test)");
    return _builder;
  }
  
  public CharSequence createRunStat(final BatterySent s) {
    CharSequence _xblockexpression = null;
    {
      EObject body = s.getSent();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (body instanceof EqualSent) {
        if ((body instanceof EqualSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new BatterySentence(");
          CharSequence _createRunStat = this.createRunStat(((EqualSent)body));
          _builder.append(_createRunStat, "");
          _builder.append(" , this.app, this.drone)");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (body instanceof GreaterSent) {
          if ((body instanceof GreaterSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new BatterySentence(");
            CharSequence _createRunStat = this.createRunStat(((GreaterSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (body instanceof LessSent) {
          if ((body instanceof LessSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new BatterySentence(");
            CharSequence _createRunStat = this.createRunStat(((LessSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("foutje");
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final SonarSent s) {
    CharSequence _xblockexpression = null;
    {
      EObject body = s.getSent();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (body instanceof EqualSent) {
        if ((body instanceof EqualSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new SonarSentence(");
          CharSequence _createRunStat = this.createRunStat(((EqualSent)body));
          _builder.append(_createRunStat, "");
          _builder.append(" , this.app, this.drone)");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (body instanceof GreaterSent) {
          if ((body instanceof GreaterSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new SonarSentence(");
            CharSequence _createRunStat = this.createRunStat(((GreaterSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (body instanceof LessSent) {
          if ((body instanceof LessSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new SonarSentence(");
            CharSequence _createRunStat = this.createRunStat(((LessSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("foutje");
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final BaroSent s) {
    CharSequence _xblockexpression = null;
    {
      EObject body = s.getSent();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (body instanceof EqualSent) {
        if ((body instanceof EqualSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new BaroSentence(");
          CharSequence _createRunStat = this.createRunStat(((EqualSent)body));
          _builder.append(_createRunStat, "");
          _builder.append(" , this.app, this.drone)");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (body instanceof GreaterSent) {
          if ((body instanceof GreaterSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new BaroSentence(");
            CharSequence _createRunStat = this.createRunStat(((GreaterSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (body instanceof LessSent) {
          if ((body instanceof LessSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new BaroSentence(");
            CharSequence _createRunStat = this.createRunStat(((LessSent)body));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("foutje");
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final EnvironmentSent s) {
    CharSequence _xblockexpression = null;
    {
      EObject sent = s.getBody();
      CharSequence _switchResult = null;
      boolean _matched = false;
      if (sent instanceof EqualSent) {
        if ((sent instanceof EqualSent)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("new WindSpdSentence(");
          CharSequence _createRunStat = this.createRunStat(((EqualSent)sent));
          _builder.append(_createRunStat, "");
          _builder.append(" , this.app, this.drone)");
          _switchResult = _builder;
        }
      }
      if (!_matched) {
        if (sent instanceof GreaterSent) {
          if ((sent instanceof GreaterSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new WindSpdSentence(");
            CharSequence _createRunStat = this.createRunStat(((GreaterSent)sent));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        if (sent instanceof LessSent) {
          if ((sent instanceof LessSent)) {
            _matched=true;
            StringConcatenation _builder = new StringConcatenation();
            _builder.append("new WindSpdSentence(");
            CharSequence _createRunStat = this.createRunStat(((LessSent)sent));
            _builder.append(_createRunStat, "");
            _builder.append(" , this.app, this.drone)");
            _switchResult = _builder;
          }
        }
      }
      if (!_matched) {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("foutje");
        _switchResult = _builder;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public CharSequence createRunStat(final DistanceUnit s) {
    CharSequence _switchResult = null;
    boolean _matched = false;
    if (s instanceof METER) {
      if ((s instanceof METER)) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        CharSequence _createRunStat = this.createRunStat(((METER)s));
        _builder.append(_createRunStat, "");
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (s instanceof KILOMETER) {
        if ((s instanceof KILOMETER)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          CharSequence _createRunStat = this.createRunStat(((KILOMETER)s));
          _builder.append(_createRunStat, "");
          _switchResult = _builder;
        }
      }
    }
    if (!_matched) {
      if (s instanceof MILLIMETER) {
        if ((s instanceof MILLIMETER)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          CharSequence _createRunStat = this.createRunStat(((MILLIMETER)s));
          _builder.append(_createRunStat, "");
          _switchResult = _builder;
        }
      }
    }
    if (!_matched) {
      if (s instanceof CENTIMETER) {
        if ((s instanceof CENTIMETER)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          CharSequence _createRunStat = this.createRunStat(((CENTIMETER)s));
          _builder.append(_createRunStat, "");
          _switchResult = _builder;
        }
      }
    }
    if (!_matched) {
      StringConcatenation _builder = new StringConcatenation();
      _switchResult = _builder;
    }
    return _switchResult;
  }
  
  public CharSequence createRunStat(final TimeUnit s) {
    CharSequence _switchResult = null;
    boolean _matched = false;
    if (s instanceof SECONDS) {
      if ((s instanceof SECONDS)) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        CharSequence _createRunStat = this.createRunStat(((SECONDS)s));
        _builder.append(_createRunStat, "");
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (s instanceof MINUTES) {
        if ((s instanceof MINUTES)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          CharSequence _createRunStat = this.createRunStat(((MINUTES)s));
          _builder.append(_createRunStat, "");
          _switchResult = _builder;
        }
      }
    }
    if (!_matched) {
      if (s instanceof HOUR) {
        if ((s instanceof HOUR)) {
          _matched=true;
          StringConcatenation _builder = new StringConcatenation();
          CharSequence _createRunStat = this.createRunStat(((HOUR)s));
          _builder.append(_createRunStat, "");
          _switchResult = _builder;
        }
      }
    }
    if (!_matched) {
      StringConcatenation _builder = new StringConcatenation();
      _switchResult = _builder;
    }
    return _switchResult;
  }
  
  public CharSequence createRunStat(final SECONDS sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Second(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final MINUTES sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Minute(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final HOUR sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Hour(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final METER sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Meter(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final KILOMETER sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Kilometer(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final MILLIMETER sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Millimeter(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final CENTIMETER sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Centimeter(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
  
  public CharSequence createRunStat(final PercentUnit sent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("new Percent(");
    String _value = sent.getValue();
    _builder.append(_value, "");
    _builder.append(")");
    return _builder;
  }
}
